t=open('/tmp/live_index.html',encoding='utf-8').read()
print('الطول:',len(t))
print('أول 30 حرف:',repr(t[:30]))
print('DOCTYPE في البداية؟', t.lstrip().startswith('<!DOCTYPE'))
print('<style> عدد:',t.count('<style'),'| </style> عدد:',t.count('</style>'))
i=t.find('<style>');j=t.find('</style>')
print('مواضع style:',i,j)
css=t[i+7:j]
print('طول CSS:',len(css))
print('تعليقات /* :',css.count('/*'),'| */ :',css.count('*/'),'| متوازن:',css.count('/*')==css.count('*/'))
print('ظهور </ داخل CSS (يغلق style مبكرًا):',css.count('</'))
print('هل <body موجود:', '<body' in t)
print('CSS أول 120 حرف:',repr(css[:120]))
print('CSS آخر 120 حرف:',repr(css[-120:]))
